# Midterm Practical
## Name: Olivia Hinson
Date: **9/16/2020**
Course: *CIS 376*

In [1]:
# Import modules to use for midterm
import numpy as np

In [2]:
# Store CSV file in variable
filename = r'<path to file>\Midterm_Practical.csv'

# Convert CSV file to array
temp = np.genfromtxt(filename, delimiter = ',')

In [3]:
# Calculate sum of Low Temperature Values (Degrees F)
sum = np.nansum(temp)
print('Sum: %.3f' % sum)

Sum: 1687.000


In [4]:
# Count values in Low Temperature Values (Degrees F) 
count = np.size(temp)
print('Count of values: ', count)

Count of values:  60


In [5]:
# Calculate mean of Low Temperature Values (Degrees F)
mean = np.nanmean(temp)
print('Mean: %.3f' % mean)

Mean: 28.593


In [6]:
# Calculate median of Low Temperature Values (Degrees F)
median = np.nanmedian(temp)
print('Median: %.3f' % median)

Median: 27.900


In [7]:
# Calculate range of Low Temperature Values (Degrees F)
min = np.nanmin(temp)
max = np.nanmax(temp)

range = max - min

print('Range: %.3f' % range)

Range: 5.000


In [8]:
# Calculate and display Q1, Q3, and IQR of Low Temperature Values (Degrees F)
q1 = np.nanpercentile(temp, 25)
q3 = np.nanpercentile(temp, 75)

iqr = q3 - q1

print('Q1: %.3f' % q1)
print('Q3: %.3f' % q3)
print('IQR: %.3f' % iqr)

Q1: 27.400
Q3: 29.450
IQR: 2.050


In [9]:
# Calculate standard deviation of Low Temperature Values (Degrees F)
std = np.nanstd(temp)
print('Standard deviation: %.3f' % std)

Standard deviation: 1.462


In [10]:
# Calculate variance of Low Temperature Values (Degrees F)
var = np.nanvar(temp)
print('Variance: %.3f' % var)

Variance: 2.137


In [11]:
# Print all items from Low Temperature Values (Degrees F)
print('Low Temperature Values (Degrees F):')
print(temp)

Low Temperature Values (Degrees F):
[[27.8 27.3 27.9 29.7]
 [27.7 27.3 28.  29.8]
 [27.6 27.3 28.1 30. ]
 [27.6 27.4 28.2 30.2]
 [27.5 27.4 28.3 30.4]
 [27.5 27.4 28.4 30.6]
 [27.4 27.4 28.5 30.8]
 [27.4 27.5 28.6 31. ]
 [27.4 27.5 28.7 31.2]
 [27.3 27.6 28.8 31.4]
 [27.3 27.6 29.  31.6]
 [27.3 27.7 29.1 31.8]
 [27.3 27.7 29.2 32. ]
 [27.3 27.8 29.4 32.3]
 [27.3 27.9 29.5  nan]]


In [12]:
# Sort items in Low Temperature Values (Degrees F) and print result
sort = np.sort(temp, axis = 0)
print('Sorted array:')
print(sort)

Sorted array:
[[27.3 27.3 27.9 29.7]
 [27.3 27.3 28.  29.8]
 [27.3 27.3 28.1 30. ]
 [27.3 27.4 28.2 30.2]
 [27.3 27.4 28.3 30.4]
 [27.3 27.4 28.4 30.6]
 [27.4 27.4 28.5 30.8]
 [27.4 27.5 28.6 31. ]
 [27.4 27.5 28.7 31.2]
 [27.5 27.6 28.8 31.4]
 [27.5 27.6 29.  31.6]
 [27.6 27.7 29.1 31.8]
 [27.6 27.7 29.2 32. ]
 [27.7 27.8 29.4 32.3]
 [27.8 27.9 29.5  nan]]
